web:
  build: .
  command: /usr/local/bin/docker.sh
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - ./src:/src

db:
  image: mongo:3.0.2
  env_file:
    - env
  ports:
    - "27017:27017"
